<?php
  require(__DIR__.'/global.php');

  $pm->Test("2019-05-19", "2019-05-20");
?>


<!-- INSERT INTO `pm_services` (`id`, `service_name`, `service_ticket_name`, `service_price_gross`, `service_price_net`, `service_expiry`, `service_cash`, `service_card`, `service_account`, `service_snap`, `service_fuel`, `service_author`, `service_created`, `service_update_author`, `service_campus`, `service_meal_amount`, `service_shower_amount`, `service_vehicles`, `service_group`, `service_etpid`, `service_active`, `service_discount_amount`, `service_wifi_amount`, `service_deleted`, `service_settlement_group`, `service_settlement_multi`) VALUES ('', '4 Day Coach Parking', '4 Day Parking Ticket', 72.00, 60.00, 96, 1, 1, 0, 0, 0, 'Ryan', '2019-05-22 13:05:30', 'Ryan', 2, 0, 4, '5', 1, 8323, 1, 4, 0, 0, 12, 4);
INSERT INTO `pm_services` (`id`, `service_name`, `service_ticket_name`, `service_price_gross`, `service_price_net`, `service_expiry`, `service_cash`, `service_card`, `service_account`, `service_snap`, `service_fuel`, `service_author`, `service_created`, `service_update_author`, `service_campus`, `service_meal_amount`, `service_shower_amount`, `service_vehicles`, `service_group`, `service_etpid`, `service_active`, `service_discount_amount`, `service_wifi_amount`, `service_deleted`, `service_settlement_group`, `service_settlement_multi`) VALUES ('', '4 Day Coach Parking*', '4 Day Parking Ticket', 72.00, 60.00, 96, 0, 0, 1, 0, 0, 'Ryan', '2019-05-22 13:03:14', 'Ryan', 2, 0, 4, '5', 1, 4854, 1, 4, 0, 0, 12, 4);
INSERT INTO `pm_services` (`id`, `service_name`, `service_ticket_name`, `service_price_gross`, `service_price_net`, `service_expiry`, `service_cash`, `service_card`, `service_account`, `service_snap`, `service_fuel`, `service_author`, `service_created`, `service_update_author`, `service_campus`, `service_meal_amount`, `service_shower_amount`, `service_vehicles`, `service_group`, `service_etpid`, `service_active`, `service_discount_amount`, `service_wifi_amount`, `service_deleted`, `service_settlement_group`, `service_settlement_multi`) VALUES ('', '4 Day Coach Parking with Meal', '4 Day Parking Ticket', 96.00, 80.00, 96, 1, 1, 0, 0, 0, 'Ryan', '2019-05-22 13:05:59', 'Ryan', 2, 4, 4, '5', 3, 8327, 1, 0, 0, 0, 13, 4);
INSERT INTO `pm_services` (`id`, `service_name`, `service_ticket_name`, `service_price_gross`, `service_price_net`, `service_expiry`, `service_cash`, `service_card`, `service_account`, `service_snap`, `service_fuel`, `service_author`, `service_created`, `service_update_author`, `service_campus`, `service_meal_amount`, `service_shower_amount`, `service_vehicles`, `service_group`, `service_etpid`, `service_active`, `service_discount_amount`, `service_wifi_amount`, `service_deleted`, `service_settlement_group`, `service_settlement_multi`) VALUES ('', '5 Day Coach Parking', '5 Day Parking Ticket', 90.00, 75.00, 120, 1, 1, 0, 0, 0, 'Ryan', '2019-05-22 15:31:04', 'Ryan', 2, 0, 5, '5', 1, 8323, 1, 5, 0, 0, 12, 5);
INSERT INTO `pm_services` (`id`, `service_name`, `service_ticket_name`, `service_price_gross`, `service_price_net`, `service_expiry`, `service_cash`, `service_card`, `service_account`, `service_snap`, `service_fuel`, `service_author`, `service_created`, `service_update_author`, `service_campus`, `service_meal_amount`, `service_shower_amount`, `service_vehicles`, `service_group`, `service_etpid`, `service_active`, `service_discount_amount`, `service_wifi_amount`, `service_deleted`, `service_settlement_group`, `service_settlement_multi`) VALUES ('', '5 Day Coach Parking*', '5 Day Parking Ticket', 90.00, 75.00, 120, 0, 0, 1, 0, 0, 'Ryan', '2019-05-22 15:31:05', 'Ryan', 2, 0, 5, '5', 1, 4854, 1, 5, 0, 0, 12, 5);
INSERT INTO `pm_services` (`id`, `service_name`, `service_ticket_name`, `service_price_gross`, `service_price_net`, `service_expiry`, `service_cash`, `service_card`, `service_account`, `service_snap`, `service_fuel`, `service_author`, `service_created`, `service_update_author`, `service_campus`, `service_meal_amount`, `service_shower_amount`, `service_vehicles`, `service_group`, `service_etpid`, `service_active`, `service_discount_amount`, `service_wifi_amount`, `service_deleted`, `service_settlement_group`, `service_settlement_multi`) VALUES ('', '5 Day Coach Parking with Meal', '5 Day Parking Ticket', 120.00, 100.00, 120, 1, 1, 0, 0, 0, 'Ryan', '2019-05-22 13:05:59', 'Ryan', 2, 5, 5, '5', 3, 8327, 1, 0, 0, 0, 13, 5);
INSERT INTO `pm_services` (`id`, `service_name`, `service_ticket_name`, `service_price_gross`, `service_price_net`, `service_expiry`, `service_cash`, `service_card`, `service_account`, `service_snap`, `service_fuel`, `service_author`, `service_created`, `service_update_author`, `service_campus`, `service_meal_amount`, `service_shower_amount`, `service_vehicles`, `service_group`, `service_etpid`, `service_active`, `service_discount_amount`, `service_wifi_amount`, `service_deleted`, `service_settlement_group`, `service_settlement_multi`) VALUES ('', '6 Day Coach Parking', '6 Day Parking Ticket', 108.00, 90.00, 144, 1, 1, 0, 0, 0, 'Ryan', '2019-05-22 15:45:26', 'Ryan', 2, 0, 6, '5', 1, 8323, 1, 6, 0, 0, 12, 6);
INSERT INTO `pm_services` (`id`, `service_name`, `service_ticket_name`, `service_price_gross`, `service_price_net`, `service_expiry`, `service_cash`, `service_card`, `service_account`, `service_snap`, `service_fuel`, `service_author`, `service_created`, `service_update_author`, `service_campus`, `service_meal_amount`, `service_shower_amount`, `service_vehicles`, `service_group`, `service_etpid`, `service_active`, `service_discount_amount`, `service_wifi_amount`, `service_deleted`, `service_settlement_group`, `service_settlement_multi`) VALUES ('', '6 Day Coach Parking*', '6 Day Parking Ticket', 108.00, 90.00, 144, 0, 0, 1, 0, 0, 'Ryan', '2019-05-22 15:44:51', 'Ryan', 2, 0, 6, '5', 1, 4854, 1, 6, 0, 0, 12, 6);
INSERT INTO `pm_services` (`id`, `service_name`, `service_ticket_name`, `service_price_gross`, `service_price_net`, `service_expiry`, `service_cash`, `service_card`, `service_account`, `service_snap`, `service_fuel`, `service_author`, `service_created`, `service_update_author`, `service_campus`, `service_meal_amount`, `service_shower_amount`, `service_vehicles`, `service_group`, `service_etpid`, `service_active`, `service_discount_amount`, `service_wifi_amount`, `service_deleted`, `service_settlement_group`, `service_settlement_multi`) VALUES ('', '6 Day Coach Parking with Meal', '6 Day Parking Ticket', 144.00, 120.00, 144, 1, 1, 0, 0, 0, 'Ryan', '2019-05-22 15:44:48', 'Ryan', 2, 6, 6, '5', 3, 8327, 1, 0, 0, 0, 13, 6);
INSERT INTO `pm_services` (`id`, `service_name`, `service_ticket_name`, `service_price_gross`, `service_price_net`, `service_expiry`, `service_cash`, `service_card`, `service_account`, `service_snap`, `service_fuel`, `service_author`, `service_created`, `service_update_author`, `service_campus`, `service_meal_amount`, `service_shower_amount`, `service_vehicles`, `service_group`, `service_etpid`, `service_active`, `service_discount_amount`, `service_wifi_amount`, `service_deleted`, `service_settlement_group`, `service_settlement_multi`) VALUES ('', '7 Day Coach Parking', '7 Day Parking Ticket', 126.00, 105.00, 168, 1, 1, 0, 0, 0, 'Ryan', '2019-05-22 15:55:21', 'Ryan', 2, 0, 7, '5', 1, 8323, 1, 7, 0, 0, 12, 7);
INSERT INTO `pm_services` (`id`, `service_name`, `service_ticket_name`, `service_price_gross`, `service_price_net`, `service_expiry`, `service_cash`, `service_card`, `service_account`, `service_snap`, `service_fuel`, `service_author`, `service_created`, `service_update_author`, `service_campus`, `service_meal_amount`, `service_shower_amount`, `service_vehicles`, `service_group`, `service_etpid`, `service_active`, `service_discount_amount`, `service_wifi_amount`, `service_deleted`, `service_settlement_group`, `service_settlement_multi`) VALUES ('', '7 Day Coach Parking*', '7 Day Parking Ticket', 126.00, 105.00, 168, 0, 0, 1, 0, 0, 'Ryan', '2019-05-22 15:55:23', 'Ryan', 2, 0, 7, '5', 1, 4854, 1, 7, 0, 0, 12, 7);
INSERT INTO `pm_services` (`id`, `service_name`, `service_ticket_name`, `service_price_gross`, `service_price_net`, `service_expiry`, `service_cash`, `service_card`, `service_account`, `service_snap`, `service_fuel`, `service_author`, `service_created`, `service_update_author`, `service_campus`, `service_meal_amount`, `service_shower_amount`, `service_vehicles`, `service_group`, `service_etpid`, `service_active`, `service_discount_amount`, `service_wifi_amount`, `service_deleted`, `service_settlement_group`, `service_settlement_multi`) VALUES ('', '7 Day Coach Parking with Meal', '7 Day Parking Ticket', 168.00, 140.00, 168, 1, 1, 0, 0, 0, 'Ryan', '2019-05-22 15:55:28', 'Ryan', 2, 7, 7, '5', 3, 8327, 1, 0, 0, 0, 13, 7); -->
